In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
#for 100% jupyter notebook cell width
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
#pandas DataFrame column and row display limits
pd.set_option('max_columns', None)
pd.set_option('max_rows', None)
pd.options.display.float_format = "{:.4f}".format
from copy import deepcopy
import tempfile
import phik
import gc

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session
DIR_PATH = '/kaggle/input/posteda/'
OUTPUT_DIR = '/kaggle/working/'

/kaggle/input/posteda/credit_card_balance_avg.csv
/kaggle/input/posteda/bureau_combined.csv
/kaggle/input/posteda/previous_application.csv
/kaggle/input/posteda/POS_CASH_balance_avg.csv
/kaggle/input/posteda/application_train_dyemp_cleaned.csv
/kaggle/input/posteda/installments_payments_avg.csv

In [2]:
def save_file(df, file_name, as_csv = True, remove_old_file= False):
    file_name = file_name or next(tempfile._get_candidate_names())
    extension = '.csv' if as_csv  else '.pkl'
    
    file_name = OUTPUT_DIR + file_name + extension
    if os.path.isfile(file_name):
        print("### File exists ! ###")
        if not remove_old_file:
            return None
        print("### Removing {} ###".format(file_name))
        os.remove(file_name)
        
    if as_csv:
        df.to_csv(file_name, encoding='utf-8')
    else:
        df.to_pickle(file_name)
    print("Saved {}...".format(file_name))

In [3]:
def read_input_file(directory_path = DIR_PATH, fileName= 'application_train', displayHead = True, 
                    displayInfo = True, displayStats = True, num_rows = None, verbose=True, saveFile = True):
    '''
    Function to load the given input table
    
    Input:
        directory_path: str, default = DIR_PATH
            Path of directory in which table is stored
        fileName: str, default = application_train.csv
            Name of csv file containing the table
        displayHead: bool, default = True
            Display head for pandas dataframe
        displayInfo: bool, default = True
            Display info for pandas dataframe
        displayStats: bool, default = True
            Describe function for pandas dataframe
        num_rows: int, default = None
            Limit pandas read for debug mode or dry run
        verbose: bool, default = True
            Whether to keep verbosity or not
    '''
        
    df = pd.read_csv(directory_path + fileName +'.csv', nrows= num_rows)
   
    if verbose:
        print("Loaded {}... Dataframe contains {}".format(fileName, len(df)))
    if displayHead:
        display(df.head())
    if displayInfo:
        display(df.info(verbose=True, show_counts = True))
    if displayStats:
        display(df.describe().T)
    if saveFile:
        save_file(df, fileName)
        
    return df

In [4]:
df_app_train = read_input_file(fileName = 'application_train_dyemp_cleaned')

Loaded application_train_dyemp_cleaned... Dataframe contains 307511

,Unnamed: 0,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,100002,1,Cash loans,M,N,Y,0,202500.0000,406597.5000,24700.5000,351000.0000,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.0188,-9461,-637.0000,-3648.0000,-2120,NaN,1,1,0,1,1,0,Laborers,1.0000,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.0830,0.2630,0.1394,0.0247,0.0369,0.9720,0.6190,0.0143,0.0000,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9720,0.6343,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0000,0.0000,0.0250,0.0369,0.9720,0.6245,0.0144,0.0000,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0000,2.0000,2.0000,2.0000,-1134.0000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
1,1,100003,0,Cash loans,F,N,N,0,270000.0000,1293502.5000,35698.5000,1129500.0000,Family,State servant,Higher education,Married,House / apartment,0.0035,-16765,-1188.0000,-1186.0000,-291,NaN,1,1,0,1,1,0,Core staff,2.0000,1,1,MONDAY,11,0,0,0,0,0,0,School,0.3113,0.6220,NaN,0.0959,0.0529,0.9850,0.7960,0.0605,0.0800,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9850,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0000,0.0000,0.0968,0.0529,0.9850,0.7990,0.0608,0.0800,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,reg oper account,block of flats,0.0714,Block,No,1.0000,0.0000,1.0000,0.0000,-828.0000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,2,100004,0,Revolving loans,M,Y,Y,0,67500.0000,135000.0000,6750.0000,135000.0000,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.0100,-19046,-225.0000,-4260.0000,-2531,26.0000,1,1,1,1,1,0,Laborers,1.0000,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.5560,0.7295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,-815.0000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,3,100006,0,Cash loans,F,N,Y,0,135000.0000,312682.5000,29686.5000,297000.0000,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.0080,-19005,-3039.0000,-9830.0000,-2437,NaN,1,1,0,1,0,0,Laborers,2.0000,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.6504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0000,0.0000,2.0000,0.0000,-617.0000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,100007,0,Cash loans,M,N,Y,0,121500.0000,513000.0000,21865.5000,513000.0000,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.0287,-19932,-3038.0000,-4310.0000,-3458,NaN,1,1,0,1,0,0,Core staff,1.0000,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.3228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,-1106.0000,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 123 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    Unnamed: 0                    307511 non-null  int64
 1    SK_ID_CURR                    307511 non-null  int64
 2    TARGET                        307511 non-null  int64
 3    NAME_CONTRACT_TYPE            307511 non-null  object
 4    CODE_GENDER                   307511 non-null  object
 5    FLAG_OWN_CAR                  307511 non-null  object
 6    FLAG_OWN_REALTY               307511 non-null  object
 7    CNT_CHILDREN                  307511 non-null  int64
 8    AMT_INCOME_TOTAL              307511 non-null  float64
 9    AMT_CREDIT                    307511 non-null  float64
 10   AMT_ANNUITY                   307499 non-null  float64
 11   AMT_GOODS_PRICE               307233 non-null  float64
 12   NAME_TYPE_SUITE               306219 non-null  object
 13   NAME_INCOME_TYPE              307511 non-null  object
 14   NAME_EDUCATION_TYPE           307511 non-null  object
 15   NAME_FAMILY_STATUS            307511 non-null  object
 16   NAME_HOUSING_TYPE             307511 non-null  object
 17   REGION_POPULATION_RELATIVE    307511 non-null  float64
 18   DAYS_BIRTH                    307511 non-null  int64
 19   DAYS_EMPLOYED                 252137 non-null  float64
 20   DAYS_REGISTRATION             307511 non-null  float64
 21   DAYS_ID_PUBLISH               307511 non-null  int64
 22   OWN_CAR_AGE                   104582 non-null  float64
 23   FLAG_MOBIL                    307511 non-null  int64
 24   FLAG_EMP_PHONE                307511 non-null  int64
 25   FLAG_WORK_PHONE               307511 non-null  int64
 26   FLAG_CONT_MOBILE              307511 non-null  int64
 27   FLAG_PHONE                    307511 non-null  int64
 28   FLAG_EMAIL                    307511 non-null  int64
 29   OCCUPATION_TYPE               211120 non-null  object
 30   CNT_FAM_MEMBERS               307509 non-null  float64
 31   REGION_RATING_CLIENT          307511 non-null  int64
 32   REGION_RATING_CLIENT_W_CITY   307511 non-null  int64
 33   WEEKDAY_APPR_PROCESS_START    307511 non-null  object
 34   HOUR_APPR_PROCESS_START       307511 non-null  int64
 35   REG_REGION_NOT_LIVE_REGION    307511 non-null  int64
 36   REG_REGION_NOT_WORK_REGION    307511 non-null  int64
 37   LIVE_REGION_NOT_WORK_REGION   307511 non-null  int64
 38   REG_CITY_NOT_LIVE_CITY        307511 non-null  int64
 39   REG_CITY_NOT_WORK_CITY        307511 non-null  int64
 40   LIVE_CITY_NOT_WORK_CITY       307511 non-null  int64
 41   ORGANIZATION_TYPE             307511 non-null  object
 42   EXT_SOURCE_1                  134133 non-null  float64
 43   EXT_SOURCE_2                  306851 non-null  float64
 44   EXT_SOURCE_3                  246546 non-null  float64
 45   APARTMENTS_AVG                151450 non-null  float64
 46   BASEMENTAREA_AVG              127568 non-null  float64
 47   YEARS_BEGINEXPLUATATION_AVG   157504 non-null  float64
 48   YEARS_BUILD_AVG               103023 non-null  float64
 49   COMMONAREA_AVG                92646 non-null   float64
 50   ELEVATORS_AVG                 143620 non-null  float64
 51   ENTRANCES_AVG                 152683 non-null  float64
 52   FLOORSMAX_AVG                 154491 non-null  float64
 53   FLOORSMIN_AVG                 98869 non-null   float64
 54   LANDAREA_AVG                  124921 non-null  float64
 55   LIVINGAPARTMENTS_AVG          97312 non-null   float64
 56   LIVINGAREA_AVG                153161 non-null  float64
 57   NONLIVINGAPARTMENTS_AVG       93997 non-null   float64
 58   NONLIVINGAREA_AVG             137829 non-null  float64
 59   APARTMENTS_MODE               151450 non-null  float64
 60   BASEMENTAREA_MODE             127568 non-null  float64
 61   YEARS_BEGINEXPLUATATION_MODE  157504 non-null  float64
 62   YEARS_BUILD_MODE              103023 non-null  float64
 63   COMMONAREA_MODE               92646 non-null   float64
 64   ELEVATORS_MODE                143620 non-null  float64
 65   ENTRANCES_MODE                152683 non-null  float64
 66   FLOORSMAX_MODE                154491 non-null  float64
 67   FLOORSMIN_MODE                98869 non-null   float64
 68   LANDAREA_MODE                 124921 non-null  float64
 69   LIVINGAPARTMENTS_MODE         97312 non-null   float64
 70   LIVINGAREA_MODE               153161 non-null  float64
 71   NONLIVINGAPARTMENTS_MODE      93997 non-null   float64
 72   NONLIVINGAREA_MODE            137829 non-null  float64
 73   APARTMENTS_MEDI               151450 non-null  float64
 74   BASEMENTAREA_MEDI             127568 non-null  float64
 75   YEARS_BEGINEXPLUATATION_MEDI  157504 non-null  float64
 76   YEARS_BUILD_MEDI              103023 non-null  float64
 77   COMMONAREA_MEDI               92646 non-null   float64
 78   ELEVATORS_MEDI                143620 non-null  float64
 79   ENTRANCES_MEDI                152683 non-null  float64
 80   FLOORSMAX_MEDI                154491 non-null  float64
 81   FLOORSMIN_MEDI                98869 non-null   float64
 82   LANDAREA_MEDI                 124921 non-null  float64
 83   LIVINGAPARTMENTS_MEDI         97312 non-null   float64
 84   LIVINGAREA_MEDI               153161 non-null  float64
 85   NONLIVINGAPARTMENTS_MEDI      93997 non-null   float64
 86   NONLIVINGAREA_MEDI            137829 non-null  float64
 87   FONDKAPREMONT_MODE            97216 non-null   object
 88   HOUSETYPE_MODE                153214 non-null  object
 89   TOTALAREA_MODE                159080 non-null  float64
 90   WALLSMATERIAL_MODE            151170 non-null  object
 91   EMERGENCYSTATE_MODE           161756 non-null  object
 92   OBS_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 93   DEF_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 94   OBS_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 95   DEF_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 96   DAYS_LAST_PHONE_CHANGE        307510 non-null  float64
 97   FLAG_DOCUMENT_2               307511 non-null  int64
 98   FLAG_DOCUMENT_3               307511 non-null  int64
 99   FLAG_DOCUMENT_4               307511 non-null  int64
 100  FLAG_DOCUMENT_5               307511 non-null  int64
 101  FLAG_DOCUMENT_6               307511 non-null  int64
 102  FLAG_DOCUMENT_7               307511 non-null  int64
 103  FLAG_DOCUMENT_8               307511 non-null  int64
 104  FLAG_DOCUMENT_9               307511 non-null  int64
 105  FLAG_DOCUMENT_10              307511 non-null  int64
 106  FLAG_DOCUMENT_11              307511 non-null  int64
 107  FLAG_DOCUMENT_12              307511 non-null  int64
 108  FLAG_DOCUMENT_13              307511 non-null  int64
 109  FLAG_DOCUMENT_14              307511 non-null  int64
 110  FLAG_DOCUMENT_15              307511 non-null  int64
 111  FLAG_DOCUMENT_16              307511 non-null  int64
 112  FLAG_DOCUMENT_17              307511 non-null  int64
 113  FLAG_DOCUMENT_18              307511 non-null  int64
 114  FLAG_DOCUMENT_19              307511 non-null  int64
 115  FLAG_DOCUMENT_20              307511 non-null  int64
 116  FLAG_DOCUMENT_21              307511 non-null  int64
 117  AMT_REQ_CREDIT_BUREAU_HOUR    265992 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_DAY     265992 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_WEEK    265992 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_MON     265992 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_QRT     265992 non-null  float64
 122  AMT_REQ_CREDIT_BUREAU_YEAR    265992 non-null  float64
dtypes: float64(66), int64(41), object(16)
memory usage: 288.6+ MB

None

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,307511.0000,153755.0000,88770.9237,0.0000,76877.5000,153755.0000,230632.5000,307510.0000
SK_ID_CURR,307511.0000,278180.5186,102790.1753,100002.0000,189145.5000,278202.0000,367142.5000,456255.0000
TARGET,307511.0000,0.0807,0.2724,0.0000,0.0000,0.0000,0.0000,1.0000
CNT_CHILDREN,307511.0000,0.4171,0.7221,0.0000,0.0000,0.0000,1.0000,19.0000
AMT_INCOME_TOTAL,307511.0000,168797.9193,237123.1463,25650.0000,112500.0000,147150.0000,202500.0000,117000000.0000
AMT_CREDIT,307511.0000,599025.9997,402490.7770,45000.0000,270000.0000,513531.0000,808650.0000,4050000.0000
AMT_ANNUITY,307499.0000,27108.5739,14493.7373,1615.5000,16524.0000,24903.0000,34596.0000,258025.5000
AMT_GOODS_PRICE,307233.0000,538396.2074,369446.4605,40500.0000,238500.0000,450000.0000,679500.0000,4050000.0000
REGION_POPULATION_RELATIVE,307511.0000,0.0209,0.0138,0.0003,0.0100,0.0188,0.0287,0.0725
DAYS_BIRTH,307511.0000,-16036.9951,4363.9886,-25229.0000,-19682.0000,-15750.0000,-12413.0000,-7489.0000
DAYS_EMPLOYED,252137.0000,-2384.1693,2338.3602,-17912.0000,-3175.0000,-1648.0000,-767.0000,0.0000
DAYS_REGISTRATION,307511.0000,-4986.1225,3522.8905,-24670.0000,-7480.0000,-4504.0000,-2010.0000,0.0000
DAYS_ID_PUBLISH,307511.0000,-2994.2024,1509.4504,-7197.0000,-4299.0000,-3254.0000,-1720.0000,0.0000
OWN_CAR_AGE,104582.0000,12.0611,11.9448,0.0000,5.0000,9.0000,15.0000,91.0000
FLAG_MOBIL,307511.0000,1.0000,0.0018,0.0000,1.0000,1.0000,1.0000,1.0000
FLAG_EMP_PHONE,307511.0000,0.8199,0.3843,0.0000,1.0000,1.0000,1.0000,1.0000
FLAG_WORK_PHONE,307511.0000,0.1994,0.3995,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_CONT_MOBILE,307511.0000,0.9981,0.0432,0.0000,1.0000,1.0000,1.0000,1.0000
FLAG_PHONE,307511.0000,0.2811,0.4495,0.0000,0.0000,0.0000,1.0000,1.0000
FLAG_EMAIL,307511.0000,0.0567,0.2313,0.0000,0.0000,0.0000,0.0000,1.0000
CNT_FAM_MEMBERS,307509.0000,2.1527,0.9107,1.0000,2.0000,2.0000,3.0000,20.0000
REGION_RATING_CLIENT,307511.0000,2.0525,0.5090,1.0000,2.0000,2.0000,2.0000,3.0000
REGION_RATING_CLIENT_W_CITY,307511.0000,2.0315,0.5027,1.0000,2.0000,2.0000,2.0000,3.0000
HOUR_APPR_PROCESS_START,307511.0000,12.0634,3.2658,0.0000,10.0000,12.0000,14.0000,23.0000
REG_REGION_NOT_LIVE_REGION,307511.0000,0.0151,0.1221,0.0000,0.0000,0.0000,0.0000,1.0000
REG_REGION_NOT_WORK_REGION,307511.0000,0.0508,0.2195,0.0000,0.0000,0.0000,0.0000,1.0000
LIVE_REGION_NOT_WORK_REGION,307511.0000,0.0407,0.1975,0.0000,0.0000,0.0000,0.0000,1.0000
REG_CITY_NOT_LIVE_CITY,307511.0000,0.0782,0.2684,0.0000,0.0000,0.0000,0.0000,1.0000
REG_CITY_NOT_WORK_CITY,307511.0000,0.2305,0.4211,0.0000,0.0000,0.0000,0.0000,1.0000
LIVE_CITY_NOT_WORK_CITY,307511.0000,0.1796,0.3838,0.0000,0.0000,0.0000,0.0000,1.0000
EXT_SOURCE_1,134133.0000,0.5021,0.2111,0.0146,0.3340,0.5060,0.6753,0.9630
EXT_SOURCE_2,306851.0000,0.5144,0.1911,0.0000,0.3926,0.5660,0.6636,0.8550
EXT_SOURCE_3,246546.0000,0.5109,0.1948,0.0005,0.3706,0.5350,0.6690,0.8960
APARTMENTS_AVG,151450.0000,0.1174,0.1082,0.0000,0.0577,0.0876,0.1486,1.0000
BASEMENTAREA_AVG,127568.0000,0.0884,0.0824,0.0000,0.0442,0.0763,0.1122,1.0000
YEARS_BEGINEXPLUATATION_AVG,157504.0000,0.9777,0.0592,0.0000,0.9766,0.9814,0.9870,1.0000
YEARS_BUILD_AVG,103023.0000,0.7525,0.1133,0.0000,0.6870,0.7554,0.8230,1.0000
COMMONAREA_AVG,92646.0000,0.0446,0.0760,0.0000,0.0078,0.0211,0.0515,1.0000
ELEVATORS_AVG,143620.0000,0.0789,0.1346,0.0000,0.0000,0.0000,0.1200,1.0000
ENTRANCES_AVG,152683.0000,0.1498,0.1001,0.0000,0.0690,0.1380,0.2069,1.0000
FLOORSMAX_AVG,154491.0000,0.2263,0.1446,0.0000,0.1667,0.1667,0.3333,1.0000
FLOORSMIN_AVG,98869.0000,0.2319,0.1614,0.0000,0.0833,0.2083,0.3750,1.0000
LANDAREA_AVG,124921.0000,0.0663,0.0812,0.0000,0.0187,0.0481,0.0856,1.0000
LIVINGAPARTMENTS_AVG,97312.0000,0.1008,0.0926,0.0000,0.0504,0.0756,0.1210,1.0000
LIVINGAREA_AVG,153161.0000,0.1074,0.1106,0.0000,0.0453,0.0745,0.1299,1.0000
NONLIVINGAPARTMENTS_AVG,93997.0000,0.0088,0.0477,0.0000,0.0000,0.0000,0.0039,1.0000
NONLIVINGAREA_AVG,137829.0000,0.0284,0.0695,0.0000,0.0000,0.0036,0.0277,1.0000
APARTMENTS_MODE,151450.0000,0.1142,0.1079,0.0000,0.0525,0.0840,0.1439,1.0000
BASEMENTAREA_MODE,127568.0000,0.0875,0.0843,0.0000,0.0407,0.0746,0.1124,1.0000
YEARS_BEGINEXPLUATATION_MODE,157504.0000,0.9770,0.0646,0.0000,0.9766,0.9814,0.9870,1.0000
YEARS_BUILD_MODE,103023.0000,0.7596,0.1101,0.0000,0.6990,0.7646,0.8237,1.0000
COMMONAREA_MODE,92646.0000,0.0426,0.0744,0.0000,0.0072,0.0190,0.0490,1.0000
ELEVATORS_MODE,143620.0000,0.0745,0.1323,0.0000,0.0000,0.0000,0.1208,1.0000
ENTRANCES_MODE,152683.0000,0.1452,0.1010,0.0000,0.0690,0.1380,0.2069,1.0000
FLOORSMAX_MODE,154491.0000,0.2223,0.1437,0.0000,0.1667,0.1667,0.3333,1.0000
FLOORSMIN_MODE,98869.0000,0.2281,0.1612,0.0000,0.0833,0.2083,0.3750,1.0000
LANDAREA_MODE,124921.0000,0.0650,0.0817,0.0000,0.0166,0.0458,0.0841,1.0000
LIVINGAPARTMENTS_MODE,97312.0000,0.1056,0.0979,0.0000,0.0542,0.0771,0.1313,1.0000
LIVINGAREA_MODE,153161.0000,0.1060,0.1118,0.0000,0.0427,0.0731,0.1252,1.0000
NONLIVINGAPARTMENTS_MODE,93997.0000,0.0081,0.0463,0.0000,0.0000,0.0000,0.0039,1.0000
NONLIVINGAREA_MODE,137829.0000,0.0270,0.0703,0.0000,0.0000,0.0011,0.0231,1.0000
APARTMENTS_MEDI,151450.0000,0.1179,0.1091,0.0000,0.0583,0.0864,0.1489,1.0000
BASEMENTAREA_MEDI,127568.0000,0.0880,0.0822,0.0000,0.0437,0.0758,0.1116,1.0000
YEARS_BEGINEXPLUATATION_MEDI,157504.0000,0.9777,0.0599,0.0000,0.9766,0.9814,0.9870,1.0000
YEARS_BUILD_MEDI,103023.0000,0.7557,0.1121,0.0000,0.6914,0.7583,0.8257,1.0000
COMMONAREA_MEDI,92646.0000,0.0446,0.0761,0.0000,0.0079,0.0208,0.0513,1.0000
ELEVATORS_MEDI,143620.0000,0.0781,0.1345,0.0000,0.0000,0.0000,0.1200,1.0000
ENTRANCES_MEDI,152683.0000,0.1492,0.1004,0.0000,0.0690,0.1380,0.2069,1.0000
FLOORSMAX_MEDI,154491.0000,0.2259,0.1451,0.0000,0.1667,0.1667,0.3333,1.0000
FLOORSMIN_MEDI,98869.0000,0.2316,0.1619,0.0000,0.0833,0.2083,0.3750,1.0000
LANDAREA_MEDI,124921.0000,0.0672,0.0822,0.0000,0.0187,0.0487,0.0868,1.0000
LIVINGAPARTMENTS_MEDI,97312.0000,0.1020,0.0936,0.0000,0.0513,0.0761,0.1231,1.0000
LIVINGAREA_MEDI,153161.0000,0.1086,0.1123,0.0000,0.0457,0.0749,0.1302,1.0000
NONLIVINGAPARTMENTS_MEDI,93997.0000,0.0087,0.0474,0.0000,0.0000,0.0000,0.0039,1.0000
NONLIVINGAREA_MEDI,137829.0000,0.0282,0.0702,0.0000,0.0000,0.0031,0.0266,1.0000
TOTALAREA_MODE,159080.0000,0.1025,0.1075,0.0000,0.0412,0.0688,0.1276,1.0000
OBS_30_CNT_SOCIAL_CIRCLE,306490.0000,1.4222,2.4010,0.0000,0.0000,0.0000,2.0000,348.0000
DEF_30_CNT_SOCIAL_CIRCLE,306490.0000,0.1434,0.4467,0.0000,0.0000,0.0000,0.0000,34.0000
OBS_60_CNT_SOCIAL_CIRCLE,306490.0000,1.4053,2.3798,0.0000,0.0000,0.0000,2.0000,344.0000
DEF_60_CNT_SOCIAL_CIRCLE,306490.0000,0.1000,0.3623,0.0000,0.0000,0.0000,0.0000,24.0000
DAYS_LAST_PHONE_CHANGE,307510.0000,-962.8590,826.8091,-4292.0000,-1570.0000,-757.0000,-274.0000,0.0000
FLAG_DOCUMENT_2,307511.0000,0.0000,0.0065,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_3,307511.0000,0.7100,0.4538,0.0000,0.0000,1.0000,1.0000,1.0000
FLAG_DOCUMENT_4,307511.0000,0.0001,0.0090,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_5,307511.0000,0.0151,0.1220,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_6,307511.0000,0.0881,0.2834,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_7,307511.0000,0.0002,0.0139,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_8,307511.0000,0.0814,0.2734,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_9,307511.0000,0.0039,0.0623,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_10,307511.0000,0.0000,0.0048,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_11,307511.0000,0.0039,0.0624,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_12,307511.0000,0.0000,0.0026,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_13,307511.0000,0.0035,0.0593,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_14,307511.0000,0.0029,0.0541,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_15,307511.0000,0.0012,0.0348,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_16,307511.0000,0.0099,0.0991,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_17,307511.0000,0.0003,0.0163,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_18,307511.0000,0.0081,0.0898,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_19,307511.0000,0.0006,0.0244,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_20,307511.0000,0.0005,0.0225,0.0000,0.0000,0.0000,0.0000,1.0000
FLAG_DOCUMENT_21,307511.0000,0.0003,0.0183,0.0000,0.0000,0.0000,0.0000,1.0000
AMT_REQ_CREDIT_BUREAU_HOUR,265992.0000,0.0064,0.0838,0.0000,0.0000,0.0000,0.0000,4.0000
AMT_REQ_CREDIT_BUREAU_DAY,265992.0000,0.0070,0.1108,0.0000,0.0000,0.0000,0.0000,9.0000
AMT_REQ_CREDIT_BUREAU_WEEK,265992.0000,0.0344,0.2047,0.0000,0.0000,0.0000,0.0000,8.0000
AMT_REQ_CREDIT_BUREAU_MON,265992.0000,0.2674,0.9160,0.0000,0.0000,0.0000,0.0000,27.0000
AMT_REQ_CREDIT_BUREAU_QRT,265992.0000,0.2655,0.7941,0.0000,0.0000,0.0000,0.0000,261.0000
AMT_REQ_CREDIT_BUREAU_YEAR,265992.0000,1.9000,1.8693,0.0000,0.0000,1.0000,3.0000,25.0000

Saved /kaggle/working/application_train_dyemp_cleaned.csv...

In [5]:
display(df_app_train.head())

,Unnamed: 0,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,100002,1,Cash loans,M,N,Y,0,202500.0000,406597.5000,24700.5000,351000.0000,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.0188,-9461,-637.0000,-3648.0000,-2120,NaN,1,1,0,1,1,0,Laborers,1.0000,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.0830,0.2630,0.1394,0.0247,0.0369,0.9720,0.6190,0.0143,0.0000,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9720,0.6343,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0000,0.0000,0.0250,0.0369,0.9720,0.6245,0.0144,0.0000,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0000,2.0000,2.0000,2.0000,-1134.0000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
1,1,100003,0,Cash loans,F,N,N,0,270000.0000,1293502.5000,35698.5000,1129500.0000,Family,State servant,Higher education,Married,House / apartment,0.0035,-16765,-1188.0000,-1186.0000,-291,NaN,1,1,0,1,1,0,Core staff,2.0000,1,1,MONDAY,11,0,0,0,0,0,0,School,0.3113,0.6220,NaN,0.0959,0.0529,0.9850,0.7960,0.0605,0.0800,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9850,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0000,0.0000,0.0968,0.0529,0.9850,0.7990,0.0608,0.0800,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,reg oper account,block of flats,0.0714,Block,No,1.0000,0.0000,1.0000,0.0000,-828.0000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,2,100004,0,Revolving loans,M,Y,Y,0,67500.0000,135000.0000,6750.0000,135000.0000,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.0100,-19046,-225.0000,-4260.0000,-2531,26.0000,1,1,1,1,1,0,Laborers,1.0000,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.5560,0.7295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,-815.0000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,3,100006,0,Cash loans,F,N,Y,0,135000.0000,312682.5000,29686.5000,297000.0000,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.0080,-19005,-3039.0000,-9830.0000,-2437,NaN,1,1,0,1,0,0,Laborers,2.0000,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.6504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0000,0.0000,2.0000,0.0000,-617.0000,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,100007,0,Cash loans,M,N,Y,0,121500.0000,513000.0000,21865.5000,513000.0000,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.0287,-19932,-3038.0000,-4310.0000,-3458,NaN,1,1,0,1,0,0,Core staff,1.0000,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.3228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,-1106.0000,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000